// ─── ASSET CONFIGURATION ─────────────────────────────────────
export const PLAYER_SPACESHIP_SRC = 'assets/images/player.png';
export const ALIEN_ENEMY_SRC = 'assets/images/alien.png';
export const LUCKY_BOX_SRC = 'assets/images/luckybox.png';
export const HEART_SRC = 'assets/images/heart.png';

// Preload images only if paths are provided
export const IMAGES = {};
export function preloadImage(key, src) {
  if (!src) return;
  const img = new Image();
  img.src = src;
  img.onload = () => { IMAGES[key] = img; };
}
preloadImage('player', PLAYER_SPACESHIP_SRC);
preloadImage('alien', ALIEN_ENEMY_SRC);
preloadImage('lucky', LUCKY_BOX_SRC);
preloadImage('heart', HEART_SRC);

// ─── WORD BANKS (scaled by difficulty, per language) ─────────

export const WORD_BANKS_EN = {
  easy: [
    'ace', 'arm', 'bat', 'bot', 'box', 'bug', 'cap', 'cow', 'cup', 'dew',
    'dig', 'dot', 'dug', 'elk', 'end', 'fan', 'fig', 'fog', 'fun', 'gap',
    'gem', 'gum', 'gut', 'hat', 'hex', 'hop', 'hub', 'ice', 'imp', 'ink',
    'ion', 'ivy', 'jam', 'jar', 'jaw', 'jet', 'jig', 'jot', 'joy', 'jug',
    'keg', 'key', 'kid', 'kit', 'lab', 'lap', 'law', 'leg', 'lid', 'lip',
    'log', 'lot', 'lug', 'map', 'mat', 'mix', 'mob', 'mop', 'mud', 'mug',
    'nap', 'net', 'nil', 'nod', 'nor', 'nut', 'oak', 'odd', 'oil', 'opt',
    'orb', 'ore', 'owl', 'pad', 'paw', 'peg', 'pen', 'pig', 'pin', 'pit',
    'pod', 'pot', 'pub', 'pun', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw',
    'red', 'rib', 'rid', 'rim', 'rip', 'rod', 'rot', 'row', 'rug', 'rum',
    'run', 'rut', 'sap', 'sat', 'saw', 'set', 'sin', 'sip', 'sit', 'six',
    'ski', 'sob', 'sod', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar',
    'tax', 'ten', 'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'top', 'tow',
    'toy', 'tub', 'tug', 'two', 'ufo', 'urn', 'van', 'vat', 'vet', 'vow',
    'wag', 'war', 'wax', 'web', 'wig', 'win', 'wit', 'wok', 'won', 'wry',
    'yak', 'yam', 'yap', 'yaw', 'yep', 'yet', 'yew', 'zip', 'zoo',
  ],
  medium: [
    'alien', 'alpha', 'amber', 'anvil', 'armor', 'atlas', 'azure', 'basin',
    'blast', 'blaze', 'blink', 'bloom', 'brain', 'brave', 'brick', 'brisk',
    'cable', 'candy', 'cedar', 'chain', 'charm', 'chess', 'chill', 'china',
    'civic', 'claim', 'clash', 'clear', 'cliff', 'climb', 'cloud', 'cobra',
    'comet', 'coral', 'craft', 'crane', 'crash', 'crest', 'crown', 'crush',
    'cubic', 'curve', 'dance', 'debug', 'delta', 'depth', 'disco', 'draft',
    'drain', 'dream', 'drift', 'drone', 'dwarf', 'eagle', 'earth', 'elder',
    'ember', 'enact', 'epoch', 'equal', 'equip', 'erupt', 'event', 'exile',
    'expat', 'extra', 'fable', 'feast', 'fiber', 'flame', 'flare', 'flash',
    'fleet', 'flint', 'float', 'flora', 'fluid', 'forge', 'forth', 'frost',
    'gleam', 'globe', 'gloom', 'glyph', 'grain', 'grape', 'grasp', 'grind',
    'guild', 'haven', 'hazel', 'helix', 'honor', 'hover', 'humid', 'hyper',
    'ivory', 'jewel', 'joust', 'knack', 'kneel', 'kraft', 'lance', 'laser',
    'latch', 'layer', 'level', 'light', 'llama', 'lodge', 'logic', 'lunar',
    'lyric', 'magic', 'manor', 'maple', 'marsh', 'medal', 'mercy', 'metal',
    'micro', 'mimic', 'minor', 'mocha', 'model', 'moral', 'mount', 'music',
    'nerve', 'noble', 'north', 'novel', 'ocean', 'omega', 'onset', 'opera',
    'optic', 'orbit', 'oxide', 'ozone', 'panic', 'patch', 'pearl', 'phase',
    'piano', 'pilot', 'pixel', 'plank', 'plant', 'plaza', 'plumb', 'plume',
    'polar', 'power', 'prawn', 'pride', 'prime', 'print', 'prism', 'prize',
    'probe', 'proof', 'prose', 'proxy', 'pulse', 'quake', 'query', 'quest',
    'quick', 'quota', 'radar', 'rapid', 'raven', 'realm', 'reign', 'relay',
    'ridge', 'rival', 'robin', 'royal', 'rumba', 'saber', 'saint', 'salsa',
    'scale', 'scout', 'serif', 'shark', 'shelf', 'shift', 'sigma', 'sleek',
    'slice', 'slope', 'smart', 'smoke', 'snake', 'snare', 'solar', 'sonic',
    'south', 'space', 'spark', 'spawn', 'spear', 'spice', 'spike', 'spine',
    'spoke', 'squad', 'stack', 'staff', 'stage', 'stain', 'stake', 'stale',
    'stamp', 'stand', 'stark', 'steam', 'steel', 'steep', 'steer', 'stern',
    'still', 'stock', 'stoic', 'stone', 'storm', 'stout', 'stove', 'strap',
    'straw', 'strip', 'stump', 'super', 'surge', 'swamp', 'sweep', 'swift',
    'sword', 'talon', 'tempo', 'tiger', 'token', 'topaz', 'total', 'tower',
    'trace', 'track', 'trade', 'trail', 'train', 'trait', 'trend', 'triad',
    'trial', 'trick', 'trine', 'troop', 'truce', 'trunk', 'trust', 'tulip',
    'turbo', 'tweed', 'twist', 'ultra', 'umbra', 'unify', 'unity', 'until',
    'upper', 'urban', 'usher', 'utter', 'vague', 'valve', 'vault', 'vigor',
    'vinyl', 'viper', 'virus', 'visor', 'vista', 'vital', 'vivid', 'vocal',
    'voice', 'voter', 'vowel', 'watch', 'water', 'wheat', 'whirl', 'wield',
    'witch', 'world', 'wound', 'wrath', 'yacht', 'yield', 'youth', 'zebra',
    'zonal',
  ],
  hard: [
    'alchemy', 'android', 'anomaly', 'apostle', 'archive', 'arsenal',
    'balance', 'banshee', 'battery', 'beacon', 'blanket', 'blazing',
    'blister', 'booster', 'capsule', 'cardiac', 'cascade', 'celsius',
    'chamber', 'channel', 'chapter', 'chariot', 'chimera', 'circuit',
    'cluster', 'coaster', 'cockpit', 'compile', 'complex', 'console',
    'contest', 'control', 'convert', 'crystal', 'current', 'crusade',
    'cyclone', 'datalog', 'decibel', 'decrypt', 'defense', 'destiny',
    'diamond', 'digital', 'discord', 'display', 'distort', 'dolphin',
    'dynasty', 'eclipse', 'element', 'embargo', 'encrypt', 'entropy',
    'episode', 'erosion', 'exploit', 'extract', 'falafel', 'fallout',
    'fantasy', 'fiction', 'firefly', 'fission', 'flannel', 'flexion',
    'formula', 'fortune', 'freight', 'furnace', 'gadget', 'galahad',
    'galaxy', 'gateway', 'genesis', 'glacier', 'granite', 'gravity',
    'griffin', 'habitat', 'halcyon', 'handoff', 'harmony', 'harvest',
    'heretic', 'hexagon', 'holster', 'horizon', 'hostile', 'hydrant',
    'hypnotic', 'iceberg', 'igniter', 'illusion', 'imaging', 'implant',
    'impulse', 'inferno', 'insight', 'install', 'ionizer', 'javelin',
    'jigsaw', 'journal', 'jubilee', 'justice', 'ketchup', 'kingdom',
    'kinetic', 'kitchen', 'lantern', 'lattice', 'leather', 'liberty',
    'lighten', 'lockout', 'maestro', 'magnate', 'mandala', 'martial',
    'masking', 'maximum', 'mercury', 'militia', 'mineral', 'mission',
    'mixture', 'modular', 'monitor', 'monsoon', 'monster', 'morning',
    'mystery', 'nebula', 'neptune', 'network', 'neutron', 'nitrate',
    'nuclear', 'nucleus', 'nullify', 'obelisk', 'obscure', 'optimal',
    'organic', 'origami', 'outpost', 'overdub', 'ovation', 'oxidize',
    'package', 'paddock', 'paradox', 'passage', 'patriot', 'payload',
    'penalty', 'pension', 'peptide', 'phantom', 'pilgrim', 'planner',
    'plastic', 'platoon', 'plunder', 'polygon', 'popcorn', 'precept',
    'presage', 'problem', 'procure', 'prodigy', 'profile', 'project',
    'protect', 'protest', 'protons', 'provoke', 'pyramid', 'quantum',
    'quarrel', 'radical', 'rampart', 'reactor', 'rebound', 'recital',
    'refract', 'refugee', 'remnant', 'require', 'resolve', 'revolve',
    'ripcord', 'runtime', 'rupture', 'salvage', 'scandal', 'scarlet',
    'scatter', 'scourge', 'segment', 'shelter', 'shuttle', 'silicon',
    'sinuous', 'skeptic', 'society', 'solvent', 'species', 'stadium',
    'stealth', 'storage', 'stratum', 'subject', 'subsidy', 'sunrise',
    'surplus', 'suspend', 'symbiont', 'synapse', 'tabloid', 'takeoff',
    'tempest', 'theorem', 'therapy', 'thermal', 'thunder', 'topiary',
    'torpedo', 'torsion', 'tracker', 'trading', 'transit', 'trigger',
    'tropics', 'tsunami', 'turbine', 'tweaker', 'twister', 'unicorn',
    'uniform', 'unleash', 'uranium', 'utility', 'vaccine', 'vagrant',
    'vanguard', 'venture', 'verdict', 'version', 'vertigo', 'veteran',
    'villain', 'vintage', 'voltage', 'vortex', 'vulture', 'warhead',
    'warrior', 'whisker', 'whistle', 'widgeon', 'wildcat', 'witness',
    'wrangle', 'xchange', 'yielded', 'zealous', 'zephyr', 'zenith',
  ],
  expert: [
    'absolute', 'abstract', 'accuracy', 'advanced', 'advisory',
    'advocate', 'aircraft', 'alchemic', 'alliance', 'almanack',
    'ambiance', 'amusedly', 'analysis', 'ancestor', 'antidote',
    'aperture', 'aquarium', 'artifice', 'assassin', 'asteroid',
    'backbone', 'bacteria', 'ballroom', 'bankrupt', 'biomorph',
    'blackout', 'blizzard', 'boundary', 'bracelet', 'broadest',
    'bulkhead', 'calendar', 'campaign', 'capsicum', 'cardinal',
    'catalyst', 'category', 'cerebral', 'champion', 'chapters',
    'checkbox', 'chromium', 'claymore', 'cliffhanger', 'cockerel',
    'collider', 'comeback', 'compiler', 'compound', 'computer',
    'concrete', 'conquest', 'contract', 'controls', 'copyhold',
    'corridor', 'crossbow', 'crucible', 'cultural', 'currency',
    'cyberpunk', 'database', 'deadline', 'debugger', 'decimate',
    'defender', 'diagnose', 'dialogue', 'diplomat', 'discount',
    'dispatch', 'dividend', 'doctrine', 'document', 'dominant',
    'dominion', 'doorstep', 'download', 'dreadful', 'dropship',
    'dynamite', 'eclipsed', 'eighteen', 'electron', 'eloquent',
    'embedded', 'emigrant', 'emphatic', 'encoding', 'endpoint',
    'enforced', 'engulfed', 'enormous', 'envelope', 'equation',
    'equipped', 'espresso', 'eternity', 'evaluate', 'eventful',
    'evidence', 'exchange', 'excludes', 'exercise', 'expedite',
    'explorer', 'external', 'extremes', 'fabulous', 'facedown',
    'failsafe', 'familiar', 'fastball', 'featured', 'feedback',
    'filename', 'finalize', 'finished', 'firmware', 'flagship',
    'flashgun', 'flexible', 'folklore', 'footstep', 'forecast',
    'forensic', 'fragment', 'freefall', 'frequent', 'frontier',
    'fullback', 'function', 'futility', 'gatepost', 'genocide',
    'gigabyte', 'gladiola', 'globetrotter', 'glossary', 'graphene',
    'greenery', 'gridlock', 'guardian', 'guidance', 'gunsmith',
    'gyratory', 'halftime', 'handbook', 'handmade', 'handover',
    'hardcore', 'hardware', 'harmonic', 'headband', 'headline',
    'helpline', 'heritage', 'highrise', 'hologram', 'homeland',
    'horseman', 'hospital', 'humanoid', 'huntsman', 'hydrogen',
    'hysteria', 'icebound', 'ignition', 'illusive', 'imagined',
    'immunity', 'imperial', 'incident', 'indulged', 'industry',
    'infrared', 'inherent', 'injector', 'innocent', 'inscribe',
    'insignia', 'integral', 'interact', 'interior', 'interval',
    'invasion', 'invented', 'invoking', 'iodizing', 'isolated',
    'issuing', 'jailbird', 'jamboree', 'japanese', 'jettison',
    'judgment', 'junction', 'keepsake', 'keyboard', 'khaki',
    'knockout', 'labeling', 'lambchop', 'landmark', 'language',
    'latitude', 'lavender', 'layabout', 'leapfrog', 'leverage',
    'licensed', 'lifelong', 'ligature', 'limiting', 'linkable',
    'literacy', 'lockdown', 'longhand', 'luminous', 'magnetic',
    'mainland', 'majestic', 'manifest', 'maritime', 'mastered',
    'matchbox', 'maximise', 'mechanic', 'medicine', 'membrane',
    'memorial', 'merchant', 'metadata', 'meteoroid', 'milepost',
    'minimize', 'minority', 'modifier', 'moisture', 'molecule',
    'momentum', 'monopoly', 'monument', 'mortgage', 'multiply',
    'mustache', 'mutation', 'navigate', 'notebook', 'nucleus',
    'numerous', 'obituary', 'obligate', 'obstacle', 'occupied',
    'offshoot', 'onscreen', 'operated', 'opponent', 'opposing',
    'optimise', 'optional', 'organism', 'original', 'orthodox',
    'outbreak', 'outreach', 'overcome', 'overhead', 'overload',
    'overlord', 'overtake', 'paradigm', 'parallel', 'paranoid',
    'particle', 'passport', 'patience', 'peculiar', 'pendulum',
    'pentagon', 'perceive', 'persists', 'personal', 'petition',
    'pipeline', 'platform', 'playback', 'pleasure', 'polished',
    'populist', 'portable', 'position', 'positive', 'powerful',
    'preclude', 'predator', 'preserve', 'pressure', 'presumed',
    'proceeds', 'producer', 'profound', 'progress', 'prohibit',
    'prologue', 'promptly', 'properly', 'proposal', 'prospect',
    'protocol', 'provider', 'publicly', 'pullback', 'punitive',
    'purchase', 'pursuant', 'puzzling', 'quadrant', 'quantify',
    'quantity', 'question', 'quotient',
  ],
};

export const WORD_BANKS_ID = {
  easy: [
    'abu', 'ada', 'air', 'aku', 'api', 'apa', 'ara', 'asa', 'bak', 'ban', 
    'bau', 'bab', 'bah', 'bel', 'bis', 'bom', 'bor', 'bos', 'bot', 'bui', 
    'bus', 'cap', 'cat', 'dam', 'dan', 'doa', 'dua', 'ego', 'era', 'flu', 
    'gas', 'gel', 'gen', 'gua', 'hak', 'hal', 'hai', 'hiu', 'iga', 'ibu', 
    'ini', 'ion', 'itu', 'jas', 'jam', 'jua', 'juz', 'jin', 'jok', 'jus', 
    'kap', 'kas', 'kah', 'kol', 'kok', 'kos', 'kue', 'lah', 'lap', 'las', 
    'lem', 'les', 'luk', 'mau', 'mak', 'mas', 'mat', 'mie', 'mur', 'nol', 
    'nya', 'oli', 'ons', 'pos', 'pak', 'pen', 'pas', 'per', 'pir', 'pon', 
    'pun', 'rak', 'ram', 'ras', 'rel', 'rem', 'rim', 'rok', 'rit', 'roh', 
    'ruh', 'ria', 'rua', 'sah', 'sak', 'sal', 'sap', 'sel', 'sen', 'sok', 
    'sup', 'sih', 'tam', 'teh', 'tik', 'tim', 'tol', 'top', 'tua', 'tuk', 
    'ubi', 'ufo', 'uji', 'vas', 'wah', 'zat',
  ],
  medium: [
    'abjad', 'absen', 'acuan', 'acung', 'admin', 'agama', 'agen', 'ahli', 
    'ajaib', 'akbar', 'akhir', 'akrab', 'alam', 'alien', 'alih', 'aman', 
    'ambil', 'ampuh', 'ampun', 'ancam', 'andal', 'aneka', 'angka', 'angin', 
    'antar', 'apung', 'arwah', 'asing', 'atom', 'awasi', 'awan', 'bakat', 
    'bakar', 'bakti', 'balok', 'bambu', 'bantu', 'baris', 'batas', 'batin', 
    'bayar', 'bebas', 'bedah', 'bekal', 'belah', 'benar', 'benci', 'benda', 
    'berat', 'besar', 'bijak', 'bilah', 'bilas', 'bioma', 'bisik', 'bobot', 
    'bocor', 'buang', 'buaya', 'budak', 'bukit', 'bulan', 'bulat', 'bumi', 
    'bumbu', 'bunga', 'buruk', 'butir', 'cabai', 'cacat', 'cagar', 'cair', 
    'calon', 'camat', 'candi', 'catat', 'cekik', 'celah', 'cepat', 'cerah', 
    'cetak', 'cipta', 'cocok', 'corak', 'cuaca', 'cubit', 'curah', 'dahan', 
    'damai', 'danau', 'darah', 'darat', 'dasar', 'data', 'daun', 'debu', 
    'dekat', 'delta', 'demam', 'derap', 'desas', 'dewan', 'didik', 'dinas', 
    'domba', 'dunia', 'dusun', 'edisi', 'egois', 'eksak', 'elang', 'emas', 
    'ember', 'emosi', 'empat', 'endap', 'epik', 'error', 'fajar', 'fakta', 
    'fase', 'fatal', 'fauna', 'fenom', 'fiksi', 'fisik', 'flora', 'fokus', 
    'forum', 'foto', 'fosil', 'gagas', 'gajah', 'galak', 'galur', 'garis', 
    'garuk', 'gasal', 'gaya', 'gelar', 'gelap', 'gema', 'gempa', 'genap', 
    'gerak', 'gigit', 'gila', 'ginjal', 'gosip', 'gugus', 'habis', 'hadir', 
    'hafal', 'hakim', 'halal', 'hantu', 'harap', 'harga', 'hari', 'hasil', 
    'hebat', 'hemat', 'henti', 'hewan', 'hibah', 'hidup', 'hijau', 'hilir', 
    'hitam', 'hukum', 'hutan', 'ideal', 'iklan', 'iklim', 'ilham', 'ilmu', 
    'imaji', 'indah', 'info', 'ingat', 'ingin', 'input', 'intan', 'inti', 
    'irama', 'iring', 'isi', 'jamur', 'jarak', 'jarum', 'jatuh', 'jauh', 
    'jelas', 'jenis', 'jeruk', 'jihad', 'jilid', 'jiwa', 'judul', 'juluk', 
    'jumat', 'jurus', 'kabar', 'kabut', 'kaca', 'kacau', 'kadar', 'kado', 
    'kalah', 'kamar', 'kapal', 'karya', 'karsa', 'kasus', 'kasur', 'kawat', 
    'kaya', 'kejar', 'kelas', 'keras', 'kerja', 'ketat', 'kilat', 'kimia', 
    'kisah', 'klaim', 'klinis', 'kobar', 'kode', 'kokoh', 'kolam', 'komet', 
    'komik', 'konon', 'kopra', 'kota', 'kotak', 'krisis', 'kritis', 'kubah', 
    'kubis', 'kulit', 'kuman', 'kumis', 'kunci', 'kursi', 'kutub', 'lacak', 
    'lahan', 'lahir', 'laju', 'lakon', 'lampu', 'lapar', 'lapor', 'latar', 
    'layak', 'layar', 'lebah', 'lebur', 'legal', 'leher', 'lekas', 'lemah', 
    'letak', 'lewat', 'licik', 'lidah', 'lilin', 'lipat', 'logam', 'logika', 
    'lokal', 'lomba', 'loncat', 'lari', 'luar', 'lubang', 'lukis', 'lunak', 
    'lunas', 'lurus', 'macam', 'macan', 'mahal', 'mahir', 'main', 'majas', 
    'maju', 'makam', 'makan', 'makin', 'malam', 'malah', 'mampu', 'mandi', 
    'manis', 'marah', 'marak', 'marga', 'masa', 'masuk', 'matang', 'mawar', 
    'maya', 'medis', 'megah', 'meja', 'merah', 'mesin', 'meteor', 'mikro', 
    'milik', 'mimpi', 'minat', 'minim', 'mirip', 'misil', 'mitos', 'mobil', 
    'modal', 'model', 'modis', 'mogok', 'moral', 'motif', 'motor', 'muara', 
    'muda', 'mudah', 'mufakat', 'muka', 'mulai', 'mulia', 'mulus', 'mulut', 
    'muncul', 'murni', 'musik', 'musim', 'mutu', 'nafas', 'nakal', 'nalar', 
    'nama', 'nanas', 'napas', 'nasib', 'nekat', 'nenek', 'nikah', 'nilai', 
    'noda', 'nomor', 'norma', 'nyala', 'nyata', 'oasis', 'obat', 'obor', 
    'obral', 'objek', 'optik', 'orbit', 'organ', 'otak', 'oval', 'pacar', 
    'padat', 'paham', 'pajak', 'pakar', 'paksa', 'palu', 'panas', 'panel', 
    'panik', 'pantai', 'papan', 'pasar', 'pasir', 'pasti', 'paten', 'patuh', 
    'pecah', 'pedas', 'peka', 'peluk', 'pena', 'penuh', 'peran', 'perak', 
    'pergi', 'perlu', 'pesan', 'pesat', 'peta', 'petak', 'petir', 'pilar', 
    'pilih', 'pintu', 'piring', 'pisau', 'planet', 'polda', 'pohon', 'puisi', 
    'pujian', 'pundi', 'pusat', 'putar', 'putih', 'putra', 'putri', 'racun', 
    'radar', 'radio', 'ragam', 'rajin', 'rahasia', 'raksasa', 'rapat', 'rasio', 
    'real', 'rebah', 'redam', 'rekam', 'rekan', 'rekat', 'relai', 'remah', 
    'remaja', 'renang', 'resah', 'resmi', 'retak', 'riang', 'ribut', 'rilis', 
    'robek', 'robot', 'roda', 'roket', 'ruang', 'rubah', 'rudal', 'rukun', 
    'rumah', 'rumit', 'rumus', 'rusa', 'rusuk', 'sabuk', 'sadar', 'sains', 
    'sakit', 'saksi', 'salah', 'saldo', 'salut', 'samar', 'sama', 'sandi', 
    'saraf', 'satwa', 'sayap', 'sebab', 'sebut', 'sedih', 'sehat', 'sejenak', 
    'sekat', 'selang', 'semak', 'sempit', 'semua', 'senat', 'sendi', 'seni', 
    'senja', 'senyum', 'serap', 'serat', 'seru', 'sesi', 'setara', 'siang', 
    'siap', 'sibuk', 'sifat', 'siklus', 'sikat', 'silang', 'sinar', 'sipil', 
    'siram', 'sisa', 'sisir', 'skala', 'solid', 'sorot', 'sosial', 'sosok', 
    'spasi', 'stabil', 'sudut', 'suhu', 'sulit', 'sulur', 'sumber', 'sunyi', 
    'surat', 'surya', 'susah', 'susul', 'susun', 'swasta', 'syaraf', 'syarat', 
    'tabel', 'tabir', 'tabu', 'tagih', 'tajam', 'taktik', 'takut', 'taman', 
    'tamu', 'tanah', 'tanda', 'tanjung', 'tanpa', 'tapak', 'tarif', 'tebal', 
    'tebing', 'tebu', 'teduh', 'tegas', 'teguh', 'teknik', 'teks', 'tekad', 
    'teluk', 'telur', 'teman', 'tempa', 'tempo', 'temu', 'tenar', 'tenda', 
    'tentu', 'teori', 'tepat', 'tepi', 'terang', 'teras', 'terik', 'terka', 
    'terus', 'tetas', 'tidak', 'tikar', 'tiket', 'timah', 'timur', 'tinta', 
    'tiup', 'tokoh', 'tolak', 'tomat', 'tonik', 'topan', 'topik', 'total', 
    'tragis', 'tugas', 'tuhan', 'tuju', 'tujuh', 'tukar', 'tulam', 'tulis', 
    'tulus', 'tumor', 'tunas', 'tunggu', 'turis', 'turun', 'tusuk', 'tutur', 
    'uang', 'uap', 'ubah', 'ucap', 'udara', 'udel', 'ujung', 'ukiran', 'ulama', 
    'ulang', 'ular', 'ulas', 'umat', 'umum', 'umur', 'undi', 'unik', 'unsur', 
    'untung', 'upaya', 'urat', 'urus', 'urut', 'usaha', 'usang', 'usia', 
    'usul', 'utama', 'utuh', 'utus', 'virus', 'vokal', 'wacana', 'wadah', 
    'wajib', 'wajah', 'waktu', 'walau', 'warga', 'warna', 'wasit', 'watak', 
    'yakhin', 'yakin', 'yakni', 'yatim', 'zona',
  ],
  hard: [
    'absolut', 'adiluhung', 'alamiah', 'alur', 'amanat', 'anggota', 'anggrek', 
    'angkasa', 'apotek', 'aturan', 'ayunan', 'bagian', 'bakteri', 'balasan', 
    'bandara', 'barokah', 'batasan', 'batin', 'bayangan', 'bekerja', 'belajar', 
    'belanja', 'bendera', 'bentuk', 'berani', 'berarti', 'berbuat', 'berguna', 
    'berhak', 'berlian', 'bersatu', 'bertapa', 'betapa', 'bicara', 'bintang', 
    'biologi', 'bisikan', 'bongkar', 'buatan', 'budiman', 'bungkusan', 'buronan', 
    'buritan', 'cahaya', 'cairan', 'candaan', 'catatan', 'cemara', 'cemburu', 
    'cendana', 'centang', 'ceroboh', 'cetakan', 'ciptaan', 'cobaan', 'cumbuan', 
    'curahan', 'dagang', 'dalang', 'dampak', 'daratan', 'darurat', 'dataran', 
    'delapan', 'dermaga', 'desain', 'detektif', 'devisa', 'dewata', 'dimensi', 
    'dinamis', 'dinamit', 'dinding', 'dingin', 'diploma', 'dipukul', 'dirawat', 
    'dorongan', 'dukun', 'dzikir', 'edukasi', 'ekonomi', 'eksotis', 'elemen', 
    'empati', 'energi', 'engkau', 'entitas', 'episode', 'erotis', 'etika', 
    'faedah', 'faham', 'faktor', 'fantasi', 'filosof', 'fisik', 'format', 
    'fusi', 'gading', 'galaksi', 'galian', 'gandum', 'ganjar', 'ganteng', 
    'garda', 'garuda', 'gawang', 'gedong', 'gegabah', 'gejolak', 'gelagar', 
    'genetik', 'genting', 'geologi', 'geraham', 'gerakan', 'gerhana', 'getaran', 
    'gradasi', 'gunung', 'habitat', 'hablur', 'hancur', 'harimau', 'harmoni', 
    'halaman', 'haluan', 'hiasan', 'hiburan', 'hidung', 'hikmah', 'hilang', 
    'himpun', 'hindar', 'holografi', 'horison', 'hormat', 'hubung', 'hukum', 
    'hunian', 'ibadah', 'identik', 'idaman', 'ikatan', 'ikhlas', 'ilmiah', 
    'imajinasi', 'impian', 'indeks', 'indera', 'infeksi', 'inovasi', 'insting', 
    'inti', 'intrik', 'irisan', 'isyarat', 'jagat', 'jajaran', 'jaminan', 
    'janda', 'janggal', 'jangkar', 'janjiku', 'japri', 'jasmani', 'jatuhan', 
    'jejaring', 'jendela', 'jenderal', 'julukan', 'jupiter', 'jurusan', 
    'kabaret', 'kabinet', 'kacang', 'kacamata', 'kadal', 'kaedah', 'kakaktua', 
    'kaleng', 'kalimat', 'kamera', 'kampus', 'kantin', 'kanvas', 'kapten', 
    'karang', 'karisma', 'ksatria', 'kasturi', 'katalog', 'kelabu', 'kelamin', 
    'kemeja', 'kenangan', 'kendali', 'kening', 'kental', 'kepada', 'kerabat', 
    'kerajaan', 'kerang', 'kering', 'kertas', 'khusus', 'kiasan', 'kilang', 
    'kinerja', 'klasik', 'klimaks', 'kocak', 'kodrat', 'komando', 'komedi', 
    'komet', 'komodo', 'kompas', 'konsep', 'konser', 'kornea', 'kosong', 
    'kranium', 'kristal', 'kuadrat', 'kualitas', 'kuantum', 'kuburan', 'kucing', 
    'kudeta', 'kudus', 'kultur', 'kuning', 'kurnia', 'kurung', 'labirin', 
    'lacak', 'ladang', 'lautan', 'layang', 'legiun', 'lelang', 'lembah', 
    'lembing', 'letusan', 'libur', 'lisensi', 'lokasi', 'loreng', 'lorong', 
    'luapan', 'lumrah', 'lutut', 'mabrur', 'maestro', 'mafhum', 'magnet', 
    'mahkota', 'makelar', 'maklum', 'mampir', 'mandiri', 'mangga', 'manggis', 
    'manual', 'marabah', 'markas', 'maut', 'melacak', 'menawan', 'menteri', 
    'menuai', 'merdeka', 'mereka', 'mesiu', 'metode', 'mineral', 'misteri', 
    'mistis', 'mitologi', 'molekul', 'montir', 'muatan', 'mukjizat', 'mutiara', 
    'nabiah', 'nakhoda', 'naluri', 'nanar', 'nastar', 'negara', 'nelayan', 
    'neraka', 'ngarai', 'nirwana', 'nominal', 'normal', 'novelis', 'nubuat', 
    'nuklir', 'nyamuk', 'obeng', 'objektif', 'oknum', 'operasi', 'optimal', 
    'orbit', 'orkestra', 'pakaian', 'paman', 'panitia', 'pantau', 'pantun', 
    'paparan', 'paralel', 'paramedis', 'pasukan', 'patung', 'pejuang', 'pelangi', 
    'pelatuk', 'pelikan', 'pelopor', 'pemuda', 'penanda', 'pendeta', 'penjaga', 
    'penjuru', 'pentas', 'perabot', 'perahu', 'perajin', 'perekat', 'periode', 
    'perisai', 'perkasa', 'permata', 'persada', 'pesanan', 'pesawat', 'peserta', 
    'pesona', 'pidana', 'pijakan', 'pikiran', 'pilhan', 'pimpinan', 'pinang', 
    'pionir', 'piramid', 'piutang', 'plastik', 'plester', 'polemik', 'polis', 
    'pondasi', 'prajurit', 'praktek', 'presisi', 'pribadi', 'program', 'propana', 
    'protein', 'provinsi', 'psikis', 'pusaka', 'putaran', 'radius', 'rahasia', 
    'rambut', 'ranjau', 'ranjang', 'rantai', 'ranting', 'rasial', 'reaksi', 
    'realita', 'recehan', 'reduksi', 'referat', 'regresi', 'rekanan', 'rekor', 
    'rencana', 'renung', 'resep', 'residu', 'respon', 'risalah', 'ritme', 
    'riwayat', 'rujukan', 'rumput', 'rumusan', 'rute', 'sabana', 'sabun', 
    'sadis', 'safari', 'sajian', 'saklar', 'salam', 'saluran', 'samudra', 
    'sandang', 'sanksi', 'sarjana', 'sasaran', 'satelit', 'saudara', 'sawah', 
    'sedotan', 'sejarah', 'sejenak', 'sekolah', 'sekte', 'sektor', 'selatan', 
    'selimut', 'selokan', 'semesta', 'seminar', 'sendok', 'sengketa', 'senjata', 
    'sensasi', 'sensor', 'senter', 'sentral', 'seorang', 'sepatu', 'serabut', 
    'seram', 'serapan', 'serdadu', 'serigala', 'sering', 'setelan', 'sewa', 
    'siaran', 'siluman', 'simbol', 'simfoni', 'sindrom', 'sinus', 'sistem', 
    'sketsa', 'skripsi', 'skrup', 'slang', 'sobekan', 'sombong', 'sorot', 
    'spesial', 'standar', 'statis', 'stasiun', 'stigma', 'stroke', 'subjek', 
    'sukses', 'sumbu', 'sundulan', 'sungai', 'sunting', 'suram', 'surga', 
    'swasta', 'sweter', 'syahid', 'syafka', 'syafaat', 'tabiat', 'tagihan', 
    'tahanan', 'takdir', 'taksi', 'tameng', 'tamparan', 'tangkas', 'tangki', 
    'target', 'taring', 'tatapan', 'telinga', 'tembaga', 'tempat', 'tendang', 
    'tenggat', 'teratai', 'teriak', 'terkini', 'termal', 'teror', 'tersisa', 
    'tiduran', 'timbangan', 'tongkat', 'tragedi', 'tropis', 'tsunami', 'tukang', 
    'tulisan', 'tumbal', 'tunggal', 'turnamen', 'tutupan', 'udang', 'ulasan', 
    'ulet', 'umpan', 'untaian', 'upacara', 'urusan', 'utusan', 'variasi', 
    'vendor', 'ventilasi', 'verbal', 'vertikal', 'veteran', 'vihara', 'vila', 
    'virus', 'vokal', 'volume', 'vonis', 'wacana', 'wawasan', 'wayang', 
    'yayasan', 'zamrud',
  ],
  expert: [
    'abnormal', 'adaptasi', 'administrasi', 'algoritma', 'ambisius', 'anomali', 
    'antarbudaya', 'antariksa', 'antisipasi', 'aplikasi', 'arsitektur', 'atmosfer', 
    'autentik', 'bahagia', 'belantara', 'bendaharawan', 'benderang', 'berkembang', 
    'bersahabat', 'birokrasi', 'candrawinata', 'caturwulan', 'cendekiawan', 
    'cenderawasih', 'cemerlang', 'dekomposisi', 'demokratis', 'demonstrasi', 
    'destinasi', 'diagonal', 'didaktis', 'digitalisasi', 'dinosaurus', 'diplomatik', 
    'diskriminasi', 'distorsi', 'distribusi', 'dwibahasa', 'efisiensi', 'ekuivalen', 
    'eksperimen', 'eksplorasi', 'eksploitasi', 'ekstraterestrial', 'elektronik', 
    'elektromagnetik', 'emansipasi', 'ensiklopedia', 'epidemiologi', 'eukaliptus', 
    'evaluasi', 'fenomena', 'fundamental', 'fungsionalitas', 'gambaran', 'geografi', 
    'geopolitik', 'globalisasi', 'gotongroyong', 'gravitasi', 'harmonisasi', 
    'hemisfer', 'heterogen', 'hipotesis', 'homogen', 'horizontal', 'hubungan', 
    'identifikasi', 'ideologi', 'imajinasi', 'implikasi', 'indikator', 'individu', 
    'informasi', 'infrastruktur', 'inisiatif', 'inovatif', 'inspirasi', 'instrumen', 
    'integrasi', 'intelijen', 'interaksi', 'interpretasi', 'intervensi', 'investasi', 
    'investigasi', 'jembatan', 'jurnalistik', 'kacamata', 'kalibrasi', 'kalkulasi', 
    'karbohidrat', 'karnivora', 'kasawari', 'khatulistiwa', 'keadilan', 
    'keanekaragaman', 'kebahagiaan', 'kebangsaan', 'keberadaan', 'keberanian', 
    'kebersihan', 'kebijakan', 'kecerdasan', 'kedaulatan', 'kedokteran', 
    'kegembiraan', 'keharmonisan', 'kehidupan', 'keikutsertaan', 'keistimewaan', 
    'kejayaan', 'kejelasan', 'kejuaraan', 'kekeluargaan', 'kekuatan', 'kelancaran', 
    'kelangsungan', 'kelayakan', 'kelelahan', 'kelembutan', 'kemajemukan', 
    'kemajuan', 'kemakmuran', 'kemandirian', 'kemanusiaan', 'kemampuan', 
    'kemerdekaan', 'kemewahan', 'kemiskinan', 'kemudahan', 'kemuliaan', 
    'kemungkinan', 'kemenangan', 'kenangan', 'kenegaraan', 'kenikmatan', 
    'kenyataan', 'kepastian', 'kepadatan', 'kepahlawanan', 'kepedulian', 
    'kepemimpinan', 'kependudukan', 'kepercayaan', 'keragaman', 'kerakyatan', 
    'kerajinan', 'kerangka', 'kerasionalan', 'kerukunan', 'kerjasama', 
    'keselamatan', 'kesehatan', 'kesejahteraan', 'keseimbangan', 'kesempatan', 
    'kesempurnaan', 'kesetaraan', 'kesulitan', 'ketersediaan', 'ketetapan', 
    'keuntungan', 'keunggulan', 'kewajiban', 'kewarganegaraan', 'kewibawaan', 
    'kewirausahaan', 'klasifikasi', 'kolaborasi', 'kombinasi', 'komoditas', 
    'komparatif', 'kompetisi', 'komprehensif', 'komunikasi', 'konduktor', 
    'konferensi', 'konfigurasi', 'konfirmasi', 'konservasi', 'konstitusi', 
    'konstruktif', 'kontemporer', 'kontinental', 'kontribusi', 'koordinasi', 
    'korporasi', 'kreativitas', 'kualifikasi', 'kuantitatif', 'kurikulum', 
    'laboratorium', 'legendaris', 'legislatif', 'legitimasi', 'linguistik', 
    'literatur', 'makroekonomi', 'manifestasi', 'manipulasi', 'marginalisasi', 
    'masyarakat', 'matematika', 'mekanisasi', 'mekanisme', 'memelihara', 
    'memprogram', 'mendemonstrasikan', 'mengarungi', 'mengawasi', 'mengemukakan', 
    'mengesankan', 'mengevaluasi', 'mengidentifikasi', 'menginspirasi', 
    'mengkatalisis', 'mengkoordinasikan', 'mengoptimalkan', 'menyelenggarakan', 
    'menyempurnakan', 'metodologi', 'mikroskop', 'milenium', 'minimalisasi', 
    'mobilitas', 'modernisasi', 'modifikasi', 'monarki', 'monumental', 'motivasi', 
    'multikultural', 'musyawarah', 'nasionalisme', 'navigasi', 'negosiasi', 
    'neokolonialisme', 'nusantara', 'objektivitas', 'observasi', 'olahraga', 
    'oligarki', 'operasional', 'optimisasi', 'organisasi', 'pahlawan', 'pandemi', 
    'panorama', 'pariwisata', 'parlemen', 'partisipasi', 'patriotisme', 'pedagang', 
    'pekarangan', 'pelabuhan', 'pelaksanaan', 'pelayaran', 'pelestarian', 
    'pemandangan', 'pembangunan', 'pemeliharaan', 'pemerintah', 'pemulihan', 
    'penanganan', 'penampilan', 'pendaftaran', 'pendidikan', 'penelitian', 
    'penerapan', 'penemuan', 'pengabdian', 'pengakuan', 'pengalaman', 'pengamanan', 
    'pengamatan', 'pengawasan', 'pengendalian', 'pengembangan', 'pengetahuan', 
    'penghayatan', 'penggunaan', 'penghargaan', 'pengukuran', 'penilaian', 
    'penjelajahan', 'penyelenggaraan', 'penyelesaian', 'peninggalan', 'peningkatan', 
    'peralatan', 'perancangan', 'perbandingan', 'perbendaharaan', 'percetakan', 
    'perdamaian', 'perdagangan', 'perebutan', 'pergerakan', 'perhitungan', 
    'periklanan', 'peringatan', 'perjalanan', 'perjuangan', 'perkampungan', 
    'perkembangan', 'perkenalan', 'perlakuan', 'perlengkapan', 'perlindungan', 
    'permainan', 'pernafasan', 'pernyataan', 'perolehan', 'perpisahan', 'perputaran', 
    'persahabatan', 'persaudaraan', 'perselisihan', 'persentase', 'persetujuan', 
    'persyaratan', 'pertahanan', 'pertandingan', 'pertanyaan', 'pertimbangan', 
    'pertolongan', 'perumahan', 'perundingan', 'perusahaan', 'perwujudan', 
    'petualangan', 'polarisasi', 'populasi', 'porselen', 'portofolio', 'prasejarah', 
    'preferensi', 'prestise', 'prevensi', 'prioritas', 'probabilitas', 
    'produktivitas', 'profesionalisme', 'proklamasi', 'propaganda', 'proporsional', 
    'protokol', 'psikiater', 'psikologi', 'rasionalisasi', 'reboisasi', 'referensi', 
    'reformasi', 'regenerasi', 'rehabilitasi', 'rekomendasi', 'rekonstruksi', 
    'relaksasi', 'relevansi', 'reproduksi', 'representasi', 'reputasi', 'reservasi', 
    'resistensi', 'restorasi', 'restrukturisasi', 'revolusi', 'romantis', 
    'rutinitas', 'sandiwara', 'sanubari', 'sejahtera', 'sekulerisasi', 'selubung', 
    'semangat', 'sempadan', 'senantiasa', 'sentralisasi', 'sertifikasi', 
    'silaturahmi', 'simposium', 'sinergi', 'sinkronisasi', 'sintesis', 'sirkulasi', 
    'sistematis', 'skenario', 'solidaritas', 'sosialisasi', 'spesifikasi', 
    'spontanitas', 'stabilisasi', 'standarisasi', 'statistika', 'stratosfer', 
    'struktural', 'sutradara', 'teleskop', 'temperatur', 'terjemahan', 'teritorial', 
    'terminologi', 'toleransi', 'tradisional', 'transformasi', 'transmisi', 
    'transparansi', 'transportasi', 'ultrasonik', 'universal', 'universitas', 
    'vegetasi', 'verifikasi', 'visualisasi', 'vulkanik', 'wawancara', 'wirausaha',
  ],
};

// ─── LANGUAGE-AWARE WORD BANK GETTER ─────────────────────────
export function getWordBanks(lang) {
  return lang === 'id' ? WORD_BANKS_ID : WORD_BANKS_EN;
}

export const UI_TEXT = {
  en: {
    score: 'SCORE',
    speed: 'SPEED',
    lvl: 'LVL',
    titleLine1: 'TYPING SPACE',
    titleLine2: 'SHOOTER',
    instruction1: 'Type the words above enemies to destroy them',
    instruction2: 'Collect Lucky Boxes for buffs & Hearts for HP',
    pressStart: '[ PRESS ENTER TO START ]',
    version: 'v1.1 — ENDLESS MODE',
    gameOver: 'GAME OVER',
    finalScore: 'FINAL SCORE',
    maxSpeed: 'MAX SPEED',
    level: 'LEVEL',
    pressRestart: '[ PRESS ENTER TO RESTART ]',
    hp: 'HP',
    buffSlowmo: 'SLOW MOTION',
    buffDouble: 'DOUBLE SCORE',
    buffBomb: 'BOMB!',
    buffShield: 'SHIELD',
    buffLaser: 'AUTO LASER',
    paused: 'GAME PAUSED',
    settings: 'SETTINGS',
    language: 'LANGUAGE',
    refreshRate: 'REFRESH RATE',
    musicVolume: 'MUSIC VOLUME',
    sfxVolume: 'SFX VOLUME',
    errorShake: 'ERROR SHAKE',
    unlimited: 'UNLIMITED',
    pressEscResume: '[ PRESS ESC/ENTER TO RESUME ]',
    typeHere: '[ TYPE WORD HERE ]',
    resume: 'RESUME',
  },
  id: {
    score: 'SCORE',
    speed: 'SPEED',
    lvl: 'LVL',
    titleLine1: 'MENGETIK LUAR',
    titleLine2: 'ANGKASA',
    instruction1: 'Ketik kata di atas musuh untuk menghancurkannya',
    instruction2: 'Kumpulkan Kotak Buff & Hati untuk HP',
    pressStart: '[ TEKAN ENTER UNTUK MULAI ]',
    version: 'v1.1 — MODE TAK TERBATAS',
    gameOver: 'PERMAINAN BERAKHIR',
    finalScore: 'SKOR AKHIR',
    maxSpeed: 'KECEPATAN MAKS',
    level: 'LEVEL',
    pressRestart: '[ TEKAN ENTER UNTUK ULANG ]',
    hp: 'HP',
    buffSlowmo: 'GERAK LAMBAT',
    buffDouble: 'SKOR GANDA',
    buffBomb: 'BOM!',
    buffShield: 'PERISAI',
    buffLaser: 'LASER OTOMATIS',
    paused: 'PERMAINAN DIJEDA',
    settings: 'PENGATURAN',
    language: 'BAHASA',
    refreshRate: 'REFRESH RATE',
    musicVolume: 'VOLUME MUSIK',
    sfxVolume: 'VOLUME EFEK SUARA',
    errorShake: 'GETARAN ERROR',
    unlimited: 'UNLIMITED',
    pressEscResume: '[ TEKAN ESC/ENTER UNTUK LANJUT ]',
    typeHere: '[ KETIK KATA DI SINI ]',
    resume: 'LANJUTKAN',
  },
};

// ─── GAME CONFIGURATION ─────────────────────────────────────
export const CONFIG = {
  PLAYER_DEFAULT_HEARTS: 3,
  PLAYER_MAX_HEARTS: 5,
  BASE_FALL_SPEED: 70,           // pixels per second
  BULLET_SPEED: 1100,            // pixels per second
  BASE_ALIEN_SPAWN_MS: 2800,     // milliseconds
  LUCKY_BOX_SPAWN_MS: 12000,
  HEART_SPAWN_MS: 18000,
  BUFF_DURATION_MS: 10000,
  SPEED_UP_INTERVAL: 75,         // every N points
  SPEED_UP_FACTOR: 1.08,         // multiplier per level
  SCORE_PER_ALIEN: 10,
  ENTITY_SIZE: 42,
  PLAYER_SIZE: 52,
  MAX_PARTICLES: 200,
  STAR_COUNT: 120,
};

// ─── BUFF DEFINITIONS ────────────────────────────────────────
export const BUFF_TYPES = [
  { id: 'slowmo', nameKey: 'buffSlowmo', color: '#00bfff' },
  { id: 'double', nameKey: 'buffDouble', color: '#ffd700' },
  { id: 'bomb', nameKey: 'buffBomb', color: '#ff4400', instant: true },
  { id: 'shield', nameKey: 'buffShield', color: '#00ff88', instant: true },
  { id: 'laser', nameKey: 'buffLaser', color: '#cc44ff' },
];
