export default [
  'abnormal', 'adaptasi', 'administrasi', 'algoritma', 'ambisius', 'anomali',
  'antarbudaya', 'antariksa', 'antisipasi', 'aplikasi', 'arsitektur', 'atmosfer',
  'autentik', 'bahagia', 'belantara', 'bendaharawan', 'benderang', 'berkembang',
  'bersahabat', 'birokrasi', 'candrawinata', 'caturwulan', 'cendekiawan',
  'cenderawasih', 'cemerlang', 'dekomposisi', 'demokratis', 'demonstrasi',
  'destinasi', 'diagonal', 'didaktis', 'digitalisasi', 'dinosaurus', 'diplomatik',
  'diskriminasi', 'distorsi', 'distribusi', 'dwibahasa', 'efisiensi', 'ekuivalen',
  'eksperimen', 'eksplorasi', 'eksploitasi', 'ekstraterestrial', 'elektronik',
  'elektromagnetik', 'emansipasi', 'ensiklopedia', 'epidemiologi', 'eukaliptus',
  'evaluasi', 'fenomena', 'fundamental', 'fungsionalitas', 'gambaran', 'geografi',
  'geopolitik', 'globalisasi', 'gotongroyong', 'gravitasi', 'harmonisasi',
  'hemisfer', 'heterogen', 'hipotesis', 'homogen', 'horizontal', 'hubungan',
  'identifikasi', 'ideologi', 'imajinasi', 'implikasi', 'indikator', 'individu',
  'informasi', 'infrastruktur', 'inisiatif', 'inovatif', 'inspirasi', 'instrumen',
  'integrasi', 'intelijen', 'interaksi', 'interpretasi', 'intervensi', 'investasi',
  'investigasi', 'jembatan', 'jurnalistik', 'kacamata', 'kalibrasi', 'kalkulasi',
  'karbohidrat', 'karnivora', 'kasawari', 'khatulistiwa', 'keadilan',
  'keanekaragaman', 'kebahagiaan', 'kebangsaan', 'keberadaan', 'keberanian',
  'kebersihan', 'kebijakan', 'kecerdasan', 'kedaulatan', 'kedokteran',
  'kegembiraan', 'keharmonisan', 'kehidupan', 'keikutsertaan', 'keistimewaan',
  'kejayaan', 'kejelasan', 'kejuaraan', 'kekeluargaan', 'kekuatan', 'kelancaran',
  'kelangsungan', 'kelayakan', 'kelelahan', 'kelembutan', 'kemajemukan',
  'kemajuan', 'kemakmuran', 'kemandirian', 'kemanusiaan', 'kemampuan',
  'kemerdekaan', 'kemewahan', 'kemiskinan', 'kemudahan', 'kemuliaan',
  'kemungkinan', 'kemenangan', 'kenangan', 'kenegaraan', 'kenikmatan',
  'kenyataan', 'kepastian', 'kepadatan', 'kepahlawanan', 'kepedulian',
  'kepemimpinan', 'kependudukan', 'kepercayaan', 'keragaman', 'kerakyatan',
  'kerajinan', 'kerangka', 'kerasionalan', 'kerukunan', 'kerjasama',
  'keselamatan', 'kesehatan', 'kesejahteraan', 'keseimbangan', 'kesempatan',
  'kesempurnaan', 'kesetaraan', 'kesulitan', 'ketersediaan', 'ketetapan',
  'keuntungan', 'keunggulan', 'kewajiban', 'kewarganegaraan', 'kewibawaan',
  'kewirausahaan', 'klasifikasi', 'kolaborasi', 'kombinasi', 'komoditas',
  'komparatif', 'kompetisi', 'komprehensif', 'komunikasi', 'konduktor',
  'konferensi', 'konfigurasi', 'konfirmasi', 'konservasi', 'konstitusi',
  'konstruktif', 'kontemporer', 'kontinental', 'kontribusi', 'koordinasi',
  'korporasi', 'kreativitas', 'kualifikasi', 'kuantitatif', 'kurikulum',
  'laboratorium', 'legendaris', 'legislatif', 'legitimasi', 'linguistik',
  'literatur', 'makroekonomi', 'manifestasi', 'manipulasi', 'marginalisasi',
  'masyarakat', 'matematika', 'mekanisasi', 'mekanisme', 'memelihara',
  'memprogram', 'mendemonstrasikan', 'mengarungi', 'mengawasi', 'mengemukakan',
  'mengesankan', 'mengevaluasi', 'mengidentifikasi', 'menginspirasi',
  'mengkatalisis', 'mengkoordinasikan', 'mengoptimalkan', 'menyelenggarakan',
  'menyempurnakan', 'metodologi', 'mikroskop', 'milenium', 'minimalisasi',
  'mobilitas', 'modernisasi', 'modifikasi', 'monarki', 'monumental', 'motivasi',
  'multikultural', 'musyawarah', 'nasionalisme', 'navigasi', 'negosiasi',
  'neokolonialisme', 'nusantara', 'objektivitas', 'observasi', 'olahraga',
  'oligarki', 'operasional', 'optimisasi', 'organisasi', 'pahlawan', 'pandemi',
  'panorama', 'pariwisata', 'parlemen', 'partisipasi', 'patriotisme', 'pedagang',
  'pekarangan', 'pelabuhan', 'pelaksanaan', 'pelayaran', 'pelestarian',
  'pemandangan', 'pembangunan', 'pemeliharaan', 'pemerintah', 'pemulihan',
  'penanganan', 'penampilan', 'pendaftaran', 'pendidikan', 'penelitian',
  'penerapan', 'penemuan', 'pengabdian', 'pengakuan', 'pengalaman', 'pengamanan',
  'pengamatan', 'pengawasan', 'pengendalian', 'pengembangan', 'pengetahuan',
  'penghayatan', 'penggunaan', 'penghargaan', 'pengukuran', 'penilaian',
  'penjelajahan', 'penjelajahan', 'penyelesaian', 'peninggalan', 'peningkatan',
  'peralatan', 'perancangan', 'perbandingan', 'perbendaharaan', 'percetakan',
  'perdamaian', 'perdagangan', 'perebutan', 'pergerakan', 'perhitungan',
  'periklanan', 'peringatan', 'perjalanan', 'perjuangan', 'perkampungan',
  'perkembangan', 'perkenalan', 'perlakuan', 'perlengkapan', 'perlindungan',
  'permainan', 'pernafasan', 'pernyataan', 'perolehan', 'perpisahan', 'perputaran',
  'persahabatan', 'persaudaraan', 'perselisihan', 'persentase', 'persetujuan',
  'persyaratan', 'pertahanan', 'pertandingan', 'pertanyaan', 'pertimbangan',
  'pertolongan', 'perumahan', 'perundingan', 'perusahaan', 'perwujudan',
  'petualangan', 'polarisasi', 'populasi', 'porselen', 'portofolio', 'prasejarah',
  'preferensi', 'prestise', 'prevensi', 'prioritas', 'probabilitas',
  'produktivitas', 'profesionalisme', 'proklamasi', 'propaganda', 'proporsional',
  'protokol', 'psikiater', 'psikologi', 'rasionalisasi', 'reboisasi', 'referensi',
  'reformasi', 'regenerasi', 'rehabilitasi', 'rekomendasi', 'rekonstruksi',
  'relaksasi', 'relevansi', 'reproduksi', 'representasi', 'reputasi', 'reservasi',
  'resistensi', 'restorasi', 'restrukturisasi', 'revolusi', 'romantis',
  'rutinitas', 'sandiwara', 'sanubari', 'sejahtera', 'sekulerisasi', 'selubung',
  'semangat', 'sempadan', 'senantiasa', 'sentralisasi', 'sertifikasi',
  'silaturahmi', 'simposium', 'sinergi', 'sinkronisasi', 'sintesis', 'sirkulasi',
  'sistematis', 'skenario', 'solidaritas', 'sosialisasi', 'spesifikasi',
  'spontanitas', 'stabilisasi', 'standarisasi', 'statistika', 'stratosfer',
  'struktural', 'sutradara', 'teleskop', 'temperatur', 'terjemahan', 'teritorial',
  'terminologi', 'toleransi', 'tradisional', 'transformasi', 'transmisi',
  'transparansi', 'transportasi', 'ultrasonik', 'universal', 'universitas',
  'vegetasi', 'verifikasi', 'visualisasi', 'vulkanik', 'wawancara', 'wirausaha',
];
